spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/embedcraft
    username: root
    password: 499team3
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9093
