spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: backend-service
  # Data Source Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/embedcraft
    username: root
    password: 499team3
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis Configuration
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
#    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
#  type-aliases-package: com.embedcraft.embedcraftcore.entity
server:
  port: 9093
